baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Say NO To The Cannibis Incubator'

[markup.highlight]
noclasses = false
style = "github"

[[module.imports]]
path = "github.com/willfaught/paige"

[markup.goldmark.renderer]
unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
